title: 赵辰宇｜学术主页
page-top-title: 赵辰宇
top-section-bg-text: 赵辰宇｜学术主页
home-subtitle: 赵辰宇
copyright-text: '© 赵辰宇 2026. 保留所有权利。'
nav-home: 首页
nav-education: 教育背景
nav-experience: 研究与项目
nav-skills: 专业技能
nav-awards: 荣誉奖项
nav-publications: 学术发表
education-label: 教育背景
experience-label: 研究与项目
skills-label: 专业技能
awards-label: 荣誉与奖项
publications-label: 学术发表
menu-label: 菜单
license-link: 许可证
language-label: 语言
navigation-label: 展开或收起导航
photo-label: 赵辰宇的照片
