title: Chenyu Zhao's Homepage
page-top-title: Chenyu Zhao
top-section-bg-text: Chenyu Zhao's Homepage
home-subtitle: Chenyu Zhao
copyright-text: '© Chenyu Zhao 2026. All Rights Reserved.'
nav-home: HOME
nav-education: EDUCATION
nav-experience: EXPERIENCE
nav-skills: SKILLS
nav-awards: AWARDS
nav-publications: PUBLICATIONS
education-label: EDUCATION
experience-label: RESEARCH & PROJECTS
skills-label: SKILLS
awards-label: HONORS & AWARDS
publications-label: PUBLICATIONS
menu-label: MENU
license-link: License
language-label: Language
navigation-label: Toggle navigation
photo-label: Portrait of Chenyu Zhao
